# Generated by Django 3.2.3 on 2021-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
