# Generated by Django 3.2.3 on 2021-07-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_picture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='picture',
            new_name='photos',
        ),
    ]
