# Generated by Django 3.2.3 on 2021-08-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
