# Generated by Django 3.2.3 on 2021-09-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210821_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='lastname',
        ),
    ]
