# Generated by Django 3.2.3 on 2021-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_picture_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
