# Generated by Django 3.2.3 on 2021-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_picture_listing_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sqft',
            field=models.FloatField(),
        ),
    ]
